### ISSUE TITLE
How to execute command for this container ?

### ISSUE THREAD

**Issue by yobud** [vincentchalamon/docker#1]
Hi!

I'm trying to use your docker-compose file integrated in dunglas/api-platform
I have a problem to run commands in it...

docker-compose run --rm web php app/console ca:cl
Conflicting options: --net=host can't be used with links. This would result in undefined behavior.

and it seems that there is an ssh server at 172.17.42.1, but I can't find the associated password...

Did I miss something?

Thank you!

**Comment by vincentchalamon** [comment]
Hi,

Can you give your configuration ? I'm running this command on OS X 10.10.4 using [Docker Toolbox](https://blog.docker.com/2015/08/docker-toolbox/) without any problem.

I remember I previously had the same issue using `--net=host` option through boot2docker, and it seemed to be a boot2docker bug, I had to rollback to a previous version. Can you try it with Docker Toolbox instead ?

Thank you !

**Comment by yobud** [comment]
I don't have boot2docker neither docker toolbox, I'm on ubuntu 15.04 using docker-compose only

I just updated docker to version 1.8.1

I can do the following command : 

> docker-compose run --rm web php app/console ca:cl

only when **I didn't** previously did this one : 

> docker-compose up -d

So, if I kill the server, I'm able to do some commands in the container.

Maybe I'm doing it wrong?

Thank you for your help.

**Comment by vincentchalamon** [comment]
OK, I have the same issue. When you execute `docker-compose run`, _docker-compose_ creates a new container from the original one (_web_ in your example), and apparently tries to link it to another container using `links` option (maybe the original container, or the _db_ one).

On ubuntu, don't you have any conflict with services running on your machine on ports 80/3306 ?

The first solution is to execute your command through _docker_ itself, not _docker-compose_:

```
docker exec -i apiplatform_web_1 php app/console ca:cl
```

Project is mount in _web_ container as a volume, so you can execute commands in local as in _web_ container: `php app/console ca:cl` will have the same effect than `docker exec -i apiplatform_web_1 php app/console ca:cl` ;-)

Another solution, **less flexible**, is to use a custom _docker-compose_ configuration by creating a `docker-compose.yml` file, it will override the default configuration. You can remove the `net` option and use `links` one, for example:

``` yml
web:
    image: vincentchalamon/docker-symfony
    links:
        - db:db
    volumes:
        - .:/var/www
    tty: true

db:
    image: mysql
    environment:
        MYSQL_DATABASE: api
        MYSQL_USER: root
        MYSQL_ALLOW_EMPTY_PASSWORD: yes
```

To use this configuration, you will have to update your `parameters.yml` file to allow _web_ container accessing _db_ container as following:

``` yml
parameters:
    database_host: db
```

**Now, you won't be able to execute commands in local as `db` host doesn't exist in your system but only in containers network !** That's why this solution is less flexible… You can also use ports mapping, but your configuration will be mort complex and less flexible.

**Comment by yobud** [comment]
Hi!

Thank you for your more than complete answer!

I've no conflict with ports 80/3306 because I'm using only docker to get a server environment. That's also why I was not able to execute php commands without docker.

The docker command is working like a charm, but I was losing shell colors and I don't know if **apiplatform_web_1** will remain the same at all time.

Then I followed your second solution and decided to remove net entries in docker-compose.yml, and adding links and port mapping :

``` yml
web:
    image: vincentchalamon/symfony
    volumes:
        - .:/var/www
    ports:
        - 80:80
    links: 
        - db:db
    tty: true

db:
    image: mysql
    ports:
        - 3306:3306
    environment:
        MYSQL_DATABASE: api
        MYSQL_USER: root
        MYSQL_ALLOW_EMPTY_PASSWORD: yes
```

This way, I can run commands using docker-compose and I'm able to access the mysql server with my system clients!

Thank you very much for your time!

BTW, your docker image is really cool, simple and efficient. I did have the same result, but with so many more dirty config until now!
