### ISSUE TITLE
An HTTP request took too long to complete

### ISSUE THREAD

**Issue by tlfbrito** [vincentchalamon/docker#4]
I always get this message: 
`An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).`

after `run docker-compose up`

**Comment by vincentchalamon** [comment]
Hi, can you print your `docker-compose.yml` file please? What version of Docker do you use?

**Comment by tlfbrito** [comment]
My composer file:

```
web:
    image: vincentchalamon/symfony
    ports:
        - 8888:80
    volumes:
        - ./symfony:/var/www
    net: "host"
    tty: true
```

Docker version 1.11.1, build 5604cbe (beta for mac)
docker-compose version 1.7.1, build 0a9ab35
